# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTGFEC_cB8PWnc-0OeqdQCjpXGMHaXXb
"""

jogador = dict()
partidas = list()
jogador['nome'] = str(input('Nome do jogador: '))
tot = int(input('Quantas partidas {} jogou? '.format(jogador['nome'])))
for c in range(0, tot):
 partidas.append(int(input(f'   Quantos gols na partida {c+1}? ')))
jogador['gols'] = partidas[:]
jogador['total'] = sum(partidas)
print('-=-'*20)
print(jogador)
print('-=-'*20)
for k, v in jogador.items():
  print('O campo {} tem o valor {}.'.format(k, v))
print('-=-'*20)
print('O jogador {} jogou {} partidas.'.format(jogador['nome'], tot))
for e, u in enumerate(partidas):
  print('  == Na partida {}, fez {} gols.'.format(e+1, u))
print('Foi um total de {} gols.'.format(jogador['total']))